### ISSUE TITLE
When will Android support Java 11?

### ISSUE THREAD

**Issue by LifeIsStrange** [google/desugar_jdk_libs#3]
Sorry but I can't find up to date information on the web.

(with or without desugaring)
What I'm specifically asking is:
When will the android runtime support Dynamic class file constant aka [JEP-309](https://bugs.openjdk.java.net/browse/JDK-8177279)

This could allow optimizations for When() in Kotlin, and could allow Kotlin to support true pattern matching (destructuring in when) without increasing compilation time.
The world need this, but Kotlin can't implement it until Android gets support for it (introduced in the old Java 11).

This will also be used in the bytecode of Java 15 (when openjdk implements pattern matching) https://openjdk.java.net/jeps/8213076

Please Google, either use openjdk by default or wake up. You are hurting humanity progress.
(disclaimer: My jugement only apply to Google the legal entity, not to the employees that will read this issue).

**Comment by LifeIsStrange** [comment]
I can't even find a meta issue on AOSP tracking support for Java 11, w t f.

**Comment by JakeWharton** [comment]
This repository is for APIs implementations which has nothing to do with ART or the Dalvik file format so it's not the appropriate place to ask. You're free to file your own issue about Java 11 on the Android tracker.

**Comment by LifeIsStrange** [comment]
Thanks

**Comment by LifeIsStrange** [comment]
@JakeWharton so you could at least answer partially: when will desugaring for all Java 11 APIs will be implemented?

**Comment by JakeWharton** [comment]
Which ones are you wanting? I can prioritize anything that is needed.

The list of supported Java 11 desugarings is here: https://r8.googlesource.com/r8/+/refs/heads/master/src/main/java/com/android/tools/r8/ir/desugar/BackportedMethodRewriter.java#1474

and here: https://r8.googlesource.com/r8/+/refs/heads/master/src/main/java/com/android/tools/r8/ir/desugar/BackportedMethodRewriter.java#1643

You can also find those from Java 9 and 10 in that same file. Sadly I'm blocked on adding ones from 12, 13, and 14 until a new JDK is added to the R8 project. Hopefully I can convince them to add 14 so I can work on all 3.

Unfortunately, for now, the only way to use these methods is by writing a pure Java library against JDK 11 and then pulling that into an Android project. D8/R8 can handle Java 11 bytecode just fine. You cannot write an Android project and link against them because they are not in the android.jar. Despite my best efforts, only a paltry few APIs from Java 9 made it into R. At least they're instantly available down to API 1 thanks to D8/R8.

**Comment by LifeIsStrange** [comment]
Thank you :)

*Which ones are you wanting? *
I just wanted to know the state of things. 
I don't need any specific API for now. 
Thanks for the lists of supported apis, good to know!

**Comment by LifeIsStrange** [comment]
@JakeWharton I don't understand :m
I've read that in 2016, for Android Nougat, Android switched it's Java runtime to openjdk cf: https://arstechnica.com/tech-policy/2016/01/android-n-switches-to-openjdk-google-tells-oracle-it-is-protected-by-the-gpl/
Therefore, Google should support Java 13 out of the box. Why isn't that the case?

**Comment by JakeWharton** [comment]
> Google should support Java 13 out of the box. Why isn't that the case?

It's because it still requires work to update and integrate.

I pushed pretty hard for someone who is capable of doing the updates to spend time on it for R. For that, we got the collection static factories. Someone else pushed for Flow and we got that too. But both were barely in time. Each landed in the last 6 weeks whereas R has been in development for nine-ish months.

Java 14 will be stable and Java 15 will be ramping down when Android R goes stable. The next opportunity to ship APIs will be in Android S a year from now when Java 16 will be stable and Java 17 is ramping down.

I don't know what else to do. Please keep spamming AOSP bug tracker during every developer preview and after every release about the missing support. Ask questions on the Android team's Reddit AMAs and at Google I/O and Android Dev Summit. Be as loud as you can about this growing problem.

> It's not clear why ART hasn't totally been replaced by openjdk.

I have no insight into this, but it's easy to throw _huge_ problem wrenches into it. You first have the millions of APKs on the Play Store that will never be recompiled and the few trillion installed APKs sitting on phones which both contain Dalvik bytecode needs to run. Getting the JVM to run that would be Hard.

It's one thing to track new APIs from `java.*` and its an entirely different thing to replace the VM and blow up the entire packaging format use across the entire lifetime of Android.

> Also It would be nice to know the average performance difference between latest ART vs latest openjdk (especially with ZGC).

Well I think it's worth noting that performance is far from the only metric that's important here. No one cares when your CPU spends a bunch of time on making your code run as fast as possible because the process will be running for days or weeks. On mobile processes last minutes. And i'm sure that's only one of many other problems, but again, this is just me speculating as a normal user.

**Comment by LifeIsStrange** [comment]
Thank you for your efforts.

*It's one thing to track new APIs from java.* and its an entirely different thing to replace the VM and blow up the entire packaging format use across the entire lifetime of Android.*
Couldn't ART be kept as a fallback for old APKs made of dalvik bytecode, and otherwise use openjdk?
I guess making openjdk work with APK files (not containing dalvik bytecode) *should* be feasible.

Anyway thank you, I'm hyped for the next Android releases then and will try to be vocal about it on the bug tracker, etc.
